/** برچسب مسیرهای ادمین — مشترک بین هدر و صفحه عدم دسترسی */
export const BREADCRUMB_MAP: Record<string, string> = {
  '/admin/dashboard': 'داشبورد',
  '/admin/pulse': 'پالس وایب',
  '/admin/kpi': 'داشبورد رشد',
  '/admin/categories': 'دسته‌بندی‌ها',
  '/admin/categories/new': 'دسته جدید',
  '/admin/lists': 'لیست‌ها',
  '/admin/items': 'لیست‌ها',
  '/admin/items/new': 'موجودیت جدید',
  '/admin/items/import': 'لیست‌ها',
  '/admin/catalog': 'لیست‌ها',
  '/admin/people': 'اشخاص',
  '/admin/catalog/edit': 'ویرایش آیتم',
  '/admin/users': 'کاربران',
  '/admin/admins': 'ادمین‌ها',
  '/admin/analytics': 'آنالیتیکس',
  '/admin/suggestions': 'پیشنهادها',
  '/admin/custom/featured': 'منتخب هوم',
  '/admin/custom/sponsored': 'تبلیغات اسپانسری',
  '/admin/comments': 'داشبورد کامنت‌ها',
  '/admin/comments/all': 'همه کامنت‌ها',
  '/admin/comments/reports': 'ریپورت کامنت‌ها',
  '/admin/comments/item-reports': 'ریپورت آیتم‌ها',
  '/admin/comments/bad-words': 'کلمات ممنوع',
  '/admin/comments/violations': 'تخلفات',
  '/admin/moderation': 'صف بررسی',
  '/admin/trash': 'زباله‌دان',
  '/admin/audit': 'لاگ تغییرات',
  '/admin/settings': 'تنظیمات',
  '/admin/access-denied': 'عدم دسترسی',
};
